### ISSUE TITLE
jmh task fails

### ISSUE THREAD

**Issue by akaigoro** [akarnokd/akarnokd-misc#9]
Following command:

> sh gradlew runBenchmarks --stacktrace 

prints following diagnostics:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jmh'.
> A failure occurred while executing me.champeau.gradle.IsolatedRunner
   > Error during execution of benchmarks

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jmh'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
....
Caused by: No benchmarks to run; check the include/exclude regexps.
	at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:268)
	at org.openjdk.jmh.runner.Runner.run(Runner.java:209)
	at me.champeau.gradle.IsolatedRunner.run(IsolatedRunner.java:38)

**Comment by akarnokd** [comment]
Works for me:

`gradlew jmh -Pjmh="ShakespearePlaysScrabble"`

or if things get stuck, I kill the gradle daemons and run:

`gradlew clean jmh -Pjmh="ShakespearePlaysScrabble" --no-daemon`

I don't recommend running all benchmarks because it can take days.

**Comment by akaigoro** [comment]
can you please place this advice in the Readme file?

**Comment by akarnokd** [comment]
You are welcome to post a pr for that.
